[package]
name = "solana-feature-gate-program"
version = "0.1.0"
description = "Solana Feature Gate Program"
authors = ["Anza Technology Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/feature-gate"
readme = "../README.md"
license-file = "../LICENSE"
edition = "2021"

[package.metadata.solana]
program-id = "Feature111111111111111111111111111111111111"

[features]
bpf-entrypoint = []
test-sbf = []

[dependencies]
num_enum = "0.7.2"
shank = "0.4.2"
solana-program = "2.0.1"
spl-program-error = "0.5.0"

[dev-dependencies]
mollusk-svm = { version = "0.0.10-solana-2.0", features = ["fuzz-fd"] }
mollusk-svm-bencher = "0.0.10-solana-2.0"
solana-sdk = "2.0.1"

[lib]
crate-type = ["cdylib", "lib"]

[[bench]]
name = "compute_units"
harness = false

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
]
